name: run-wpi-many-tests
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: exec-wpi-many-tests
        run: ./run-cf-tests.sh
        shell: bash
